services:
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sst
      - POSTGRES_PASSWORD=sst
      - POSTGRES_DB=sstdb

  mongodb:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sstlogdb