spring:
  application:
    name: sst-service
  datasource:
    url: jdbc:postgresql://localhost:5432/sstdb
    username: sst
    password: sst
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  default-produces-media-type: application/json
